### ISSUE TITLE
Graph Editor: Usability Improvements

### ISSUE THREAD

**Issue by kwokcb** [AcademySoftwareFoundation/MaterialX#1398] opened 2023-07-06 13:44 UTC
This groups a set of suggestions / proposals for improving how users interact with the Graph Editor.
The hope is to take the "best" ideas and designs and incorporate them if they will help interaction / usability.

Each item below is broken down into:
* Problem: description of issue
* Proposal: Proposal to address the issue
* Sub-issue: Link to sub-issue if applicable.

Folks can add / modify each item.
Please up / down vote an item.

@lfl-eholthouser  is the main stake-holder for this.

**Comment by kwokcb** [comment] 2023-07-06 13:47
## Problem
All UI is uniformly "grey" and aesthetically "dull"
## Proposal
 Add node color themes.
## Issue
https://github.com/AcademySoftwareFoundation/MaterialX/issues/1373

**Comment by kwokcb** [comment] 2023-07-06 13:49
## Problem
It is very hard to distinguish data flow paths as they show up as overlapping lines with uniform appearance
## Proposal
From Lee Kerley: Color graph edges to help to improve readability

**Comment by kwokcb** [comment] 2023-07-06 13:51
## Problem
It is very hard to find specific node types such as inputs, outputs, renderables, and conditions
## Proposal
Add in color coding based on node-group or category. Note that this has overlap with color theming.

**Comment by kwokcb** [comment] 2023-07-06 13:56
## Problem
Text labels/ fields in the property editor and node graph are hard to distinguish from each other (e.g. for importance, for categorization etc)
## Proposal
( Pulled from #1207 from @dbsmythe )
* I'd really like for nodes to indicate what their "nodecategory" is (e.g. add or over or fractal2d) right in the node itself, drawn in boldface at the top inside the node box, e.g. below the title with the node name and above the "out" output. Without this, it's hard to look at just the graph and see what mathematical operation it's doing.
* Similarly, in the Node Property Editor, it'd be nice if the nodecatagory value (e.g. the word "add" or "over" etc) was much more prominent: boldface, a different color, or something.

**Comment by marwie** [comment] 2023-08-15 18:10
## Problem

*Connected* Inputs and Outputs don't show current (receiving or outgoing) values making it harder to debug the flow / state of a graph at a certain point ("does this input actually receive what I think it does")

![image](https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/b488131d-aac6-4cd5-8321-9669a8acc0b8)

## Proposal

Display readonly values next to `[type]`

**Comment by marwie** [comment] 2023-08-15 18:16
## Problem

When trying to resize the window sometimes the inner UI layout element gets selected (because it sets the arrow cursor on windows as well) 

## Proposal

Disable resizing behaviour of inner layout element (?)

https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/1f1347d8-2b57-460c-963b-ff5cb32647c4

**Comment by marwie** [comment] 2023-08-16 07:24
## Problem

Refreshing a graph has to be done by re-opening the file.
When debugging a graph that is generated by external tools I currently have to go to "File/Open File" and open the same graph again

## Proposal
Add shortcut to reload the currently opened graph from disc (e.g. CTRL+R or F5)

**Comment by marwie** [comment] 2023-08-16 07:27
## Problem

Invalid graph information is not displayed in the graph and just in the console window

## Proposal

Highlight nodes that are invalid / produce errors and display the error information in e.g. the Node Property Editor (?) as well

![image](https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/2ac47531-f2ab-4c4e-a30b-abbbcd0e6a0e)

**Comment by marwie** [comment] 2023-08-16 08:14
## Problem
When adding a new node with keyboard only the node list stays open and hides the newly created node which is confusing ("was the node created? where is it?")

## Proposal
Hide the node list when selecting a node and accepting with keyboard (ENTER) 

https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/896431a1-809a-4b23-889c-a1248f795a39

**Comment by marwie** [comment] 2023-08-16 08:39
## Problem

Already connected inputs have to first be disconnected to then connect to another output.

## Proposal

Allow updating input connections by dragging another output connection over the port

https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/bb4ab8ed-50da-49bf-8de1-222101aae6d8

**Comment by marwie** [comment] 2023-08-16 08:40
## Problem

Connections dont start / end at the input/output dots but instead seem to use the center of the text. This is on windows 10

## Proposal

Connections should start / end at the node edge or at the dot

![image](https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/8dd24148-85b3-4194-809a-69ff1610b58c)

**Comment by marwie** [comment] 2023-08-16 08:43
## Problem

Connections only work one-way / connections can not be made by dragging *Input* to *Output* ports

## Proposal

Allow connecting ports by dragging input over output port

https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/7d690588-e5ab-44c2-b161-f21f95e2ea0d

**Comment by marwie** [comment] 2023-08-16 10:02
## Problem
Enabled `show all inputs` toggle pushes the toggle to the end of the list which forces scrolling to hide the list again

## Proposed solution
Toggle stays at the same position and behaves more like a `unfold` header item

https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/dcf3cf9f-697a-45e5-a952-48ba051d7f41

**Comment by marwie** [comment] 2023-08-16 10:29
## Problem

Material has to be saved to see the actual material code that is being written

## Propsal

Add Viewer/Panel to display the MaterialX code that I would get when saving the graph (+1 if the code can highlight the part that I have currently selected in the visual graph + also visually mark/highlight the input nodes maybe)

**Comment by marwie** [comment] 2023-08-16 10:33
## Problem

`CTRL+S` always prompts with the filepath where the graph should be saved to (even if it was saved to a particular location already before)

## Proposal

Remember last save location and override the file with `CTRL+S` as well as add `CTRL+Shift+S` for saving to a new location

**Comment by marwie** [comment] 2023-08-16 12:14
## Problem

Graph Window doesn't show name of currently opened graph

## Proposal

Show name of currently opened graph in the window

![image](https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/388db610-9e00-449f-9ebb-bdf480cbd6c6)

**Comment by marwie** [comment] 2023-08-16 12:42
## Problem

Selecting and *cutting* a group of nodes (CTRL+X) does *sometimes* only cut the connection and sometimes paste only the nodes without the connection

## Solution

Connections should not be lost. When selecting nodes it should not just remove the connection. The nodes should be pasted in the same *connected* state as before


https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/61b42c3e-85a1-4fed-bff4-b26cc9a99aba

**Comment by marwie** [comment] 2023-08-16 17:31
## Problem
editing swizzle channels is very very slow (everything freezes for 1-2 seconds)

https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/467b4324-2c3b-492e-b340-b1d30d1b7ecb

**Comment by marwie** [comment] 2023-08-16 17:38
## Problem

Exported graphs all have position values baked in which makes the graph harder to read when trying to understand how things are connected. 

## Proposal

Add option to save without position data

**Comment by marwie** [comment] 2023-08-17 11:02
## Problem

On windows GraphView doesn't remember which graph I had opened before and where the window was on the screen

## Proposal

Remember last opened material + position on screen when starting GraphView

**Comment by marwie** [comment] 2023-08-17 12:12
## Problem
Trying to open a node_graph the first time (double click) does first compile the shader and then I have to double click again to actually open the subgraph


https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/5c8e0e34-993c-40bf-9dde-93820e436f87

**Comment by marwie** [comment] 2023-08-18 08:37
## Problem
Open graph via file association is not supported

![image](https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/830c1e18-f07f-4670-9a7a-d67b44c547e1)

**Comment by marwie** [comment] 2023-08-18 10:35
## Problem
No way to remove inputs (e.g. if I have changed some values in the standard surface shader during testing)

## Solution
Add a way to reset inputs to their default values which should also (perhaps) hide them again if "Show all inputs" is enalbed

![image](https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/b9846fd7-68f2-4d5c-86b4-f0b83b0d79f8)
![image](https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/e304893d-2f39-4a41-965f-463d439eba3c)

**Comment by marwie** [comment] 2023-08-18 10:44
## Problem
Property Editor UI is very cramped and leaves very little space between categories making it hard to read

## Proposal
Add more space between items that don't immediately belong together
For example between Category and Inputs headers should be ~half a line vertical space
Similarly it would be helpful if the buttons below Inputs (namely "Show all inputs" and "Node Info") would be pushed down half a line.
Header elements like "Category" and "Inputs" could be **bold** 

![image](https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/c4371d6d-6044-4308-aef2-badd65f8fb02)

Input elements could use the available horizontal space more properly:

![image](https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/bc75332b-4aec-4721-9d2b-7fe4dd53fb60)

Input element control items should be aligned for better readability
![image](https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/7a8ab3c1-7148-4016-b31d-3bb9020ffd8a)

**Comment by marwie** [comment] 2023-08-18 11:32
## Problem

The console window doesn't print a message when i open a new graph. This makes it difficult to understand if validation errors in the console window where caused by the newly opened graph or were from a graph previously opened.

## Proposal

Print a short message before opening a new graph to the console (e.g. `<timestamp> Opening <filename> at <filepath>` )

**Comment by marwie** [comment] 2023-08-18 11:49
## Problem
Dragging a node does not select it. I was multiple times fooled by thinking I had the node selected

## Proposal

Dragging a node should select it (especially since it visually looks selected)

https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/d91269b6-e389-4147-af64-b64669195ed0

Example from Unity ShaderGraph

https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/89eef760-2619-4aef-bc46-c7dcd1c9c328

**Comment by marwie** [comment] 2023-08-18 11:52
## Problem
Property editor doesnt reflect multi-selection. It always just displays *one* of the selected nodes

## Proposal
Property editor should render UI for all nodes selected.

https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/21db509f-b903-4eef-b33f-614bb71ce82e

**Comment by marwie** [comment] 2023-08-18 12:03
## Problem
Copy paste of a node has unexpected inputs/defaults, pasted node is in a different state

## Proposal
Copy paste should produce a copy with the same UI state

https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/eea0f386-ae01-422f-aa13-e5a46ce10a96

**Comment by marwie** [comment] 2023-08-18 12:12
## Problem
Automatic naming of nodes is confusing / misleading. E.g. creating a `constant_vector4` node for the first time is named `constant_vector4` (also reflecting the type of the node, that's good) but creating a `constant_vector4` node for the second time suddenly is named `constant_vector5` instead of `constant_vector4 (2)` or something similar explicit

![image](https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/d6e7fd6c-ad8f-40be-b87c-d53dcb4610b0)


## Proposal
Node names ending with a number (reflecting their value type) should not just increment 

- Perhaps the value type should not be included in the name but displayed differently on the node? Then it would become something like: `constant_2` and `vector3` be rendered elsewhere on the node (?)

- Slots could indicate the value type (e.g. `value` would become `value (4)` or `value (xyzw)` and `value(rgba)` ? )

https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/77ba7620-d539-465b-b02d-3a3239720b3c

Example in Unity

![image](https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/d4d81ba1-5e20-4697-9dcc-d2b712398eea)

**Comment by marwie** [comment] 2023-08-18 14:17
## Problem
Some input fields are too small for the content

## Proposal
Use the horizontal space available

somewhat related to the proposal mentioned above: https://github.com/AcademySoftwareFoundation/MaterialX/issues/1398#issuecomment-1683723538

![image](https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/eb1f7e71-d61f-4bac-bcf2-b475f5aff62f)

![image](https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/bfb470be-3c47-4675-931d-594ab4b99f8b)

**Comment by marwie** [comment] 2023-08-18 15:58
## Problem
Environment can not be changed
## Proposal
Add option to change environment map (e.g. specify a EXR or HDR texture)

**Comment by marwie** [comment] 2023-08-18 16:01
## Problem
Scroll in PropertyEditor does also zoom in viewport in some cases
Viewport interaction doesnt seem to check / play well with the scrollview 

https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/e3aab602-3fe6-44c8-86bb-9c5af8c1b613

**Comment by marwie** [comment] 2023-08-18 16:20
## Problem
Errors are hard to debug without visual indication / validation errors

## Proposal
Visualize invalid connections

![2023-08-18-181836_MaterialX_Graph_Editor-needle](https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/5cbc7c18-1dba-4655-b36e-76b29480a683)

![2023-08-18-181817_MaterialX_Graph_Editor-needle](https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/7b20cc97-a150-4932-892b-230d9a822e3a)

**Comment by marwie** [comment] 2023-08-18 16:31
## Problem
Trying to delete character in `string` field with *DELETE* key does delete the currently selected node

**Comment by marwie** [comment] 2023-08-18 16:49
## Problem

When creating a new material I find myself always creating the same basic material

## Proposal
`new` could have e.g. a `standard_surface` material already setup

or it could work like in Blender with a template material stored somewhere in the installation directory that I could also override and change to my liking

![image](https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/390cfffc-38f4-4c00-a42a-a8eb3935b758)

**Comment by marwie** [comment] 2023-08-18 17:02
## Problem
Connections sometimes *visually* work both ways but are not actually working which is very confusing when debugging

Related to the comment above: https://github.com/AcademySoftwareFoundation/MaterialX/issues/1398#issuecomment-1680203806

https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/28202f20-0e7b-4b01-a1a0-4869bd52ecc3

**Comment by marwie** [comment] 2023-08-20 13:41
## Request

Add file drop support to open a graph

https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/0ba02e5a-d0fa-43e8-b202-fb7f08a031f1

**Comment by marwie** [comment] 2023-08-21 08:06
## Problem

Editor doesnt have a file icon (the same is true for the MaterialX Viewer)


![image](https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/a141c48e-d37a-4856-bcd8-b5bce15d0d3c)

**Comment by marwie** [comment] 2023-08-21 11:10
## Problem

Inputs list unnecessary shows scrollbar

![image](https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/d82d371e-f073-4d84-9915-71953b4be3ac)

**Comment by marwie** [comment] 2023-08-21 11:12
## Problem

Alignment of output slots is not working correctly in certain cases 

![image](https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/501e1755-95fc-495b-ab68-7d091d25b099)

**Comment by marwie** [comment] 2023-08-21 13:52
## Problem

`uiname` is not used for node inputs (e.g. to name combine vector3 inputs `x y z` instead of `in1 in2 in3`)

![image](https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/7bef9b6b-a29c-4119-8eab-1bb6329ab868)

![image](https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/b47f59f2-ef36-45b1-a162-341c66abaddd)

**Comment by jstone-lucasfilm** [comment] 2023-09-12 22:14
Thanks so much for this list, @marwie and @kwokcb, and I'm marking it as a Good First Issue for our upcoming Dev Days event in October, since developers can select a single issue from this list to tackle in a short time period.

**Comment by sandersteen** [comment] 2023-10-11 02:00
> ## Problem
> Graph Window doesn't show name of currently opened graph which becomes a problem when having multiple GraphView windows open ("I want to look at the marble_material")
> 
> ## Proposal
> Show name of currently opened graph in the window (if any), e.g. `marble_material - MaterialX Graph View` title should start with the material name as it might be easily cut off otherwise, see screenshot below)
> 
> ![image](https://user-images.githubusercontent.com/5083203/261003828-388db610-9e00-449f-9ebb-bdf480cbd6c6.png)

Hey @jstone-lucasfilm , I had a quick look at this one to get myself more familiar with the document structure in MaterialX. I have a "fix" that calls `glfwSetWindowTitle` from the `Graph::drawGraph` function. I am not a big fan of this as it requires passing the GLFWwindow down from "main" to the above function call. I preferred it slightly over extracting the document out of the Graph class though, but both feel a bit mweh. 
Happy for better suggestions, or if this is the best we can do without doing bigger refactors I am happy to make a PR.

**Comment by jstone-lucasfilm** [comment] 2023-10-12 01:40
Thanks for taking a look at this one, @sandersteen, and I'm CC'ing @lfl-eholthouser for her expertise on the systems that you're asking about in this question.

**Comment by lfl-eholthouser** [comment] 2023-10-12 16:13
Hi @sandersteen! Thanks for looking at the issue. For the extracting the doc from the graph class option, would it be possible to just extract the name of the document instead of the whole document? Or are other aspects of the document needed?

**Comment by n-jay** [comment] 2023-10-21 16:21
@jstone-lucasfilm I'm thinking of having a go at issue https://github.com/AcademySoftwareFoundation/MaterialX/issues/1398#issuecomment-1680360553.
Hope that one is available.

**Comment by jstone-lucasfilm** [comment] 2023-10-25 01:09
@n-jay Thanks for taking a look at this subtask, and I'm CC'ing @kwokcb, who did some closely related work in #1499.

I believe there are aspects of the subtask (e.g. the Save/SaveAs distinction) that didn't quite make their way into the final commit for #1499, but this earlier work should make a great starting point.

**Comment by n-jay** [comment] 2023-10-25 03:37
Noted @jstone-lucasfilm, didn't notice that PR. Seems like I'd been running an outdated local main branch

> but this earlier work should make a great starting point.

Yes, some of the doubts I had about the original implementation such as the `_materialFilename` had been addressed here, so it's cool to know I've been going down the correct path. 😄 
I look forward to Bernard's response.

**Comment by kwokcb** [comment] 2023-10-27 16:01
Hi @n-jay,
- This [revision](https://github.com/AcademySoftwareFoundation/MaterialX/pull/1499/commits/447f34b2a24d3a8b6086a5e9c1df16896ddd0abc) had CTRL-S save functionality implemented.
- I think the thing to resolve is that do you allow save of file automatically loaded at startup. The premise I proposed was to not do so. Perhaps the solution is to make this situation require a file dialog prompt. Otherwise CTRL-S will overwrite without a  file dialog prompt. CTRL-SHIFT-S would be just map to the current behaviour.
- Once you have something, it might be easier to continue any follow-up in a draft PR.
- Hope this helps.

**Comment by n-jay** [comment] 2023-11-01 18:53
Noted @kwokcb 

> I think the thing to resolve is that do you allow save of file automatically loaded at startup. The premise I proposed was to not do so. Perhaps the solution is to make this situation require a file dialog prompt. Otherwise CTRL-S will overwrite without a file dialog prompt. CTRL-SHIFT-S would be just map to the current behaviour.

I see. So if I'm understanding correctly you're referring to the _last saved_ file getting loaded on startup, yes?
And the file dialogue prompt would be to manually _pick_ the required file to load at startup?
Would a **File > Open Recent** option work in this instance?

**Comment by jstone-lucasfilm** [comment] 2023-12-02 18:42
Following up on ASWF Dev Days 2023, many of these issues have been addressed (either completely or partially), so I believe we should close out this original report, and post new tasks for additional improvements that are required.

Thanks to @kwokcb and @marwie for posting this, and I believe it was a major part of the success of our Dev Days event!

**Closed by jstone-lucasfilm** 2023-12-02 18:42 UTC
Labels: good first issue
