### ISSUE TITLE
Switch nodes no longer cull unused branches in shader generation

### ISSUE THREAD

**Issue by kwokcb** [AcademySoftwareFoundation/MaterialX#1526] opened 2023-09-09 11:22 UTC
With this [PR](https://github.com/AcademySoftwareFoundation/MaterialX/pull/1522), `switch` nodes no longer optimize to use only 1 branch.

The previous logic checks for an unconnected constant value which is used to perform the optimization but was removed.
The resulting generated code is now larger since this was removed.

**Comment by jstone-lucasfilm** [comment] 2023-09-09 21:01
This is a good area for discussion, though we may want to consider this category of optimization as a future part of our "interface reduction" rules for shader generation, rather than making a special case for the switch node.

Culling generated code based on a constant input isn’t always what the user will want, as this requires shader recompilation when inputs are modified in an editor, and it seems worthwhile to make this behavior controllable by the client application.

**Comment by JGamache-autodesk** [comment] 2023-09-11 15:00
The culling behavior of the switch node was a bug introduced way back in 1.38.0 that was fixed in 1.38.8.

If you look at the node definition of the switch node:
```xml
  <nodedef name="ND_switch_float" node="switch" nodegroup="conditional">
    <input name="in1" type="float" value="0.0" />
    <input name="in2" type="float" value="0.0" />
    <input name="in3" type="float" value="0.0" />
    <input name="in4" type="float" value="0.0" />
    <input name="in5" type="float" value="0.0" />
    <input name="which" type="float" value="0.0" />
    <output name="out" type="float" defaultinput="in1" />
  </nodedef>
```
You will see no hint that leaving the `which` input unconnected will result in branch pruning.

I expect, given this node definition, that my shader will have a shader uniform parameter for the `which` input that can be driven programmatically, allowing the same shader code to be re-used between shader instance differing only on the value of that parameter.

This would make it consistent with the behavior of 99% of the nodes. The `constant` node being the one and only exception.

Now, if I were to connect a `constant` node to the `which` input, I could expect that a good constant propagation pass on the graph would end up pruning the switch node, but in this case, the user explicitly requested this behavior by connecting a constant node, it was not explicitly done without the user's consent.

My vote is to close this issue as "by design" and move on to future optimization code in the shadergen to properly handle constant propagation.

**Comment by jstone-lucasfilm** [comment] 2023-09-12 23:00
@JGamache-autodesk This sounds like a fair take to me, and I'd be interested in thoughts from @kwokcb.

**Comment by kwokcb** [comment] 2023-09-15 12:37
Sorry, if this is long winded...

Some additional context to consider:

1. Is the input "exposed" to the user to modify. If not then, we should consider this to be something that can be optimized out. For example if it's inside a nodegraph for a definition.
2.  Code generation allows for exposure for node inputs internal to a graph or not. If not exposed then this should be an optimization consideration. 
3. Performance should be considered for always having `if` or `switch` code being emitted. For example do we know that this works well for ESSL. So the optimization probably should allow for generator specific optimizations.
4. I'm not sure what this means for languages like MDL and OSL. Both are not directly executable so need to be parsed. In that context how much reuse is there as these are not strictly "shader code". 

I am not so sure about "guessing" what the user wants as there are different scenarios for code generation and not just reuse for an edit workflow.  I'm not sure you want to force a constant to be added by the user. This forces artists to consider shader optimization which could be the case but depends on how technical they are -- also as noted this may not apply to all backend generators.

I agree that performing branch pruning "under the covers" is also not a good solution but I was mostly worried that behaviour has changed. It was always intentional to prune (even before 1.38) as optimization was the only factor considered. Reversing this without an new option I don't see as any better, so agree that explicit optimization options should be added.

BTW, in addition to optimization for reuse I think that the optimization option used to produce a shader should be recorded on the `Shader` itself as the optimization option can be change dynamically.

**Comment by jstone-lucasfilm** [comment] 2023-09-23 16:55
These are good thoughts for the future, @kwokcb, and I'd recommend that we focus on improvements to the client-side controls for generated shader interfaces in MaterialX, removing the need for heuristics that apply a single set of rules to all users.  I'll close out this issue for now, and am looking forward to future discussions in this space.

**Closed by jstone-lucasfilm** 2023-09-23 16:55 UTC
