### ISSUE TITLE
Renaming some nodes crashes Graph Editor

### ISSUE THREAD

**Issue by zicher3d** [AcademySoftwareFoundation/MaterialX#1580] opened 2023-10-19 23:04 UTC
This is specific to some graphs. I don't know how to reproduce from scratch, but I have more than one graph with this issue.
Open the MTLX in the attached zip.
Open the nodegraph "NG_protein_checker_rename"
Trying to rename any of the 3 nodes highlighted below results in crash (MaterialX 1.38.8, official build from Github)

![image](https://github.com/AcademySoftwareFoundation/MaterialX/assets/7254958/6aecdfef-5bfc-4abd-af39-62de6db0b523)

[checker03 - rename_crash.zip](https://github.com/AcademySoftwareFoundation/MaterialX/files/13048313/checker03.-.rename_crash.zip)

**Comment by jstone-lucasfilm** [comment] 2024-01-09 02:01
Thanks for this report, @zicher3d.  I'm testing these repro steps in the main branch of MaterialX, and it looks like this crash has been addressed by development work for ASWF Dev Days 2023, which should become part of the pre-built binaries for MaterialX 1.38.9.

I'll go ahead and close out this report, but feel free to post new issues if you encounter crashes or unexpected behavior in future builds.

**Closed by jstone-lucasfilm** 2024-01-09 02:01 UTC
